### ISSUE TITLE
Hyperlayout simply printing out config

### ISSUE THREAD

**Issue by WoodyWoodsta** [timolins/hyperlayout#8]
**Hyper version:** 1.0.0
**OS:** Linux (elementary OS Loki)

I have the following in my `./.hyperlayout` (a bit verbose, but I intend to add more to it in the future):
```json
{
  "p2lab": [
    {
      "entry": "tab",
      "layout": [
        "gitsub-dir && cd experimental/p2lab",
        {
          "entry": "vertical",
          "layout": [ "gitsub-dir && cd experimental/p2lab && yarn run watch", "gitsub-dir && cd experimental/p2lab && yarn run serve-dev" ]
        }
      ]
    }
  ],
}
```

When I run `hyperlayout p2lab`, it simply prints out:

```text
[hyperlayout config]:{"config":{"entry":"tab","layout":[{"entry":"tab","layout":["gitsub-dir && cd experimental/p2lab",{"entry":"vertical","layout":["gitsub-dir && cd experimental/p2lab && yarn run watch","gitsub-dir && cd experimental/p2lab && yarn run serve-dev"]}]}]},"cwd":"/home"}
```

... and does not effect the defined layout. Am I doing something wrong?

**Comment by timolins** [comment]
I'm not entirely sure why it prints out the config. Are you sure you have `hyperlayout` inside `~/.hyper.js`? It still seems weird since it should detect the missing plugin (never tested it on Linux, though).

If that issue is fixed it still fails since the config is not correct. It should look like this:
```json
{
  "p2lab": [
    "gitsub-dir && cd experimental/p2lab",
    [[
      "gitsub-dir && cd experimental/p2lab && yarn run watch",
      "gitsub-dir && cd experimental/p2lab && yarn run serve-dev"
    ]]
  ]
}
```

Since you set the entry point to `tab` you can leave it out, since this it's the default anyway. `entry` only works on root level, so it's necessary to create a nested array for a split view.

**Comment by WoodyWoodsta** [comment]
Ok I understand the syntax now. I also had a trailing comma which should have blown it up.

I'm using what you have posted there and it manipulates the tabs, but not so well. I've simplified the config so that we can see what is going on, and included screenshots of the result below. Note that I am using `oh-my-zsh`, could that perhaps introduce issues?

```json
{
  "layout-test": [
    "echo one",
    [["echo two", "echo three"]]
  ]
}
```
First tab appears to do what is required.
![image](https://cloud.githubusercontent.com/assets/8268040/20844845/8f3fdf18-b8ca-11e6-9baf-938672b0e535.png)

Second tab does not do anything.
![image](https://cloud.githubusercontent.com/assets/8268040/20844848/9765ed4a-b8ca-11e6-962d-e0ed3eca4bab.png)

**Comment by timolins** [comment]
Weird. Can't really tell why this happens – I need to test this myself on a linux machine. `oh-my-zsh` shouldn't cause any troubles (I'm using it myself, and it works fine).

Does a single tab config work for you? It looks like pane-splitting is causing some issues.
```json
[[
  "echo 1",
  "echo 2"
]]
```

```sh
$ hyperlayout
```

**Comment by WoodyWoodsta** [comment]
Splits, but does not execute the second command.

![image](https://cloud.githubusercontent.com/assets/8268040/20859714/302b9efe-b96f-11e6-9eed-2e9dba6ee6ac.png)

**Comment by timolins** [comment]
Okay, thanks for your help! I will try to reproduce this bug, once I get my hands on a linux machine.

**Comment by kevingelion** [comment]
This is happening to me currently after a fresh install of Hyper on MacOS Sierra.

**Comment by timolins** [comment]
@kevingelion The thing with the config-printing or commands not executing?

**Comment by kevingelion** [comment]
The config is just printed and nothing happens. Here's my config:

```
{
  "devbox": [
    [[
      ["dashboard", "cd ~/Documents/Repositories/dashboard; git status;"],
      ["coreapi", "worker"]
    ]]
  ]
}
```

**Comment by timolins** [comment]
@kevingelion Is this still an issue, or has this been resolved in #9?

**Comment by kevingelion** [comment]
@timolins unfortunately still an issue

**Comment by timolins** [comment]
Are you using Hyper.app? I could imagine that this happens with Hyperterm.

**Comment by timolins** [comment]
Okay, I think I got the same issue since Hyper 1.0, so I was able to look into it & fix it. 🎉  At least it works for me again. Can someone confirm this?

**Comment by timolins** [comment]
@kevingelion @WoodyWoodsta

**Comment by kevingelion** [comment]
Works for me! Thanks! 🎉

**Comment by kevingelion** [comment]
So I actually noticed now that, even with your example `.hyperlayout` from the README with printing Hello and World, that only the first command will get run. So I'll type `hyperlayout` in bash, and the first pane will echo Hello, then the second pane will open but nothing will happen. I can continue adding panes and it still gets to the second and stops. Should I open another issue?

**Comment by WoodyWoodsta** [comment]
Updated hyperlayout and hyper and tried the simple test as below:

```
[[
  "echo 1",
  "echo 2"
]]
```

It's still splitting the window correctly, but both commands are being run in the first pane.

**Comment by timolins** [comment]
Great! 👍 Does anyone of you  remeber why the original Issue (Printing out the raw config) happend? Still seems to be a problem according to #12

**Comment by WoodyWoodsta** [comment]
Unfortunately I did not get to the bottom of that. If I had the time, I would dig into the module and try and find out :frowning_face:

**Comment by stereokai** [comment]
I have a fix which I could test on my Windows 10 machine. I'll submit a PR and then someone else can test it on a Mac/Linux :)

**Comment by stereokai** [comment]
I accidentally added a broken linked to the PR but fixed it now.

**Comment by jonaswindey** [comment]
I've had the same issue (printing the config) and restarting Hyper fixed the issue

**Comment by Cycymomo** [comment]
I have currently the issue (printing the config).

Windows 7 SP1
Hyper 1.3.1

zsh (with babun http://babun.github.io/)

~/.hyperlayout
`[[
  "echo 1",
  "echo 2"
]]`

❯ hyperlayout
[hyperlayout config]:{"config":{"entry":"tab","layout":[["echo 1","echo 2"]]},"cwd":"C:\\Users\\cyril.moreau"}

**Comment by RikardGehlin** [comment]
I can replicate the "printing out config" issue, by typing hyperlayout right after installing the plugin. After restarting hyper though it's gone.

I still have trouble getting hyperlayout to work though... after typing hyperlayout the window just freezes, and dev tools throws a syntax error about unexpected token in JSON.

**Comment by jondcoleman** [comment]
Also fixed by implementing this #16 by hand solved. Would be nice to get that merged.

**Comment by philoserf** [comment]
The original issue seems solved. Is this still that?

**Comment by axed** [comment]
Still happening on Windows 7 x64 with Hyper 2.0.0 - the same `.hyperlayout` file works fine on linux and macos (hyperlayout 0.2.1)

**Comment by ScriptPup** [comment]
I have the same issue, Windows 10 Hyper 2.0.0. When I run `hyperlayout` all I get is `hyperlayout config]:{"config":{"entry":"tab","layout":[["echo 'Hello'","echo 'World'"]]},"cwd":"C:\\Users\\ScriptPup"}`

My .hyperlayout file is very simple

```
[
  [
    "echo 'Hello'",
    "echo 'World'"
  ]
]
[
  [
    "echo 'Hello'",
    "echo 'World'"
  ]
]
```

**Comment by tuchk4** [comment]
Same Issue with Hyper v3

**Comment by tuchk4** [comment]
https://github.com/timolins/hyperlayout/commit/07e0a978cdb5a14aec539dd9e44f01936f13a4f9#diff-1818e7e7bdb050f4deb1fe38c76041a2L77
